/* Hardware interrupts specific to the connectivity line MCUs.
 * Based on Table 61. from ST Reference Manual RM0008. */

                IRQ     WWDG_IRQHandler
                IRQ     PVD_IRQHandler
                IRQ     TAMPER_IRQHandler
                IRQ     RTC_IRQHandler
                IRQ     FLASH_IRQHandler
                IRQ     RCC_IRQHandler
                IRQ     EXTI0_IRQHandler
                IRQ     EXTI1_IRQHandler
                IRQ     EXTI2_IRQHandler
                IRQ     EXTI3_IRQHandler
                IRQ     EXTI4_IRQHandler
                IRQ     DMA1_Channel1_IRQHandler
                IRQ     DMA1_Channel2_IRQHandler
                IRQ     DMA1_Channel3_IRQHandler
                IRQ     DMA1_Channel4_IRQHandler
                IRQ     DMA1_Channel5_IRQHandler
                IRQ     DMA1_Channel6_IRQHandler
                IRQ     DMA1_Channel7_IRQHandler
                IRQ     ADC1_2_IRQHandler
                IRQ     CAN1_TX_IRQHandler
                IRQ     CAN1_RX0_IRQHandler
                IRQ     CAN1_RX1_IRQHandler
                IRQ     CAN1_SCE_IRQHandler
                IRQ     EXTI9_5_IRQHandler
                IRQ     TIM1_BRK_IRQHandler
                IRQ     TIM1_UP_IRQHandler
                IRQ     TIM1_TRG_COM_IRQHandler
                IRQ     TIM1_CC_IRQHandler
                IRQ     TIM2_IRQHandler
                IRQ     TIM3_IRQHandler
                IRQ     TIM4_IRQHandler
                IRQ     I2C1_EV_IRQHandler
                IRQ     I2C1_ER_IRQHandler
                IRQ     I2C2_EV_IRQHandler
                IRQ     I2C2_ER_IRQHandler
                IRQ     SPI1_IRQHandler
                IRQ     SPI2_IRQHandler
                IRQ     USART1_IRQHandler
                IRQ     USART2_IRQHandler
                IRQ     USART3_IRQHandler
                IRQ     EXTI15_10_IRQHandler
                IRQ     RTCAlarm_IRQHandler
                IRQ     OTG_FS_WKUP_IRQHandler
                IRQ     Reserved_IRQHandler1    /* 43. reserved */
                IRQ     Reserved_IRQHandler2    /* 44. reserved */
                IRQ     Reserved_IRQHandler3    /* 45. reserved */
                IRQ     Reserved_IRQHandler4    /* 46. reserved */
                IRQ     Reserved_IRQHandler5    /* 47. reserved */
                IRQ     Reserved_IRQHandler6    /* 48. reserved */
                IRQ     Reserved_IRQHandler7    /* 49. reserved */
                IRQ     TIM5_IRQHandler
                IRQ     SPI3_IRQHandler
                IRQ     UART4_IRQHandler
                IRQ     UART5_IRQHandler
                IRQ     TIM6_IRQHandler
                IRQ     TIM7_IRQHandler
                IRQ     DMA2_Channel1_IRQHandler
                IRQ     DMA2_Channel2_IRQHandler
                IRQ     DMA2_Channel3_IRQHandler
                IRQ     DMA2_Channel4_IRQHandler
                IRQ     DMA2_Channel5_IRQHandler
                IRQ     ETH_IRQHandler
                IRQ     ETH_WKUP_IRQHandler
                IRQ     CAN2_TX_IRQHandler
                IRQ     CAN2_RX0_IRQHandler
                IRQ     CAN2_RX1_IRQHandler
                IRQ     CAN2_SCE_IRQHandler
                IRQ     OTG_FS_IRQHandler